### ISSUE TITLE
Cafe page padding

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#17]
I know you looked at this, but can we adjust a little? See attached PDF. If this is something I can do, let me know :)
[Cafe Page Padding.pdf](https://github.com/deringer/foods-for-life/files/41437/Cafe.Page.Padding.pdf)

**Comment by deringer** [comment]
Yes, this can be managed from the row's advanced design settings - you'll want to adjust the column's left and right padding as necessary.

Keep in mind that the content will always center itself vertically depending on the height of the content so you may find yourself endlessly fiddling with the left and right padding to get the top and bottom padding similar.

This will also mean that for those sections that have slightly more text, you'll end up with slightly taller containers. If you want, though, I can tweak the minimum height value of each row so that's consistent across all. It's currently set to `280px`, which covers all of the sections as they are now.

**Comment by leah-wuttke** [comment]
Can you set it to 310px high?
