### ISSUE TITLE
Integrate Campaign Monitor subscribe field

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#25]
Do you have enough info/access to do this?

**Comment by deringer** [comment]
You mentioned that you were going to look into this 'later in the week' a couple of weeks ago, and I'm pretty sure we talked about you giving me access to their CM, but I hadn't seen any emails. Turns out GMail had kindly moved it to spam.

I'm about to push up changes for pretty much all of the other issues you've opened. I'll have a look at the excel invoice and campaign monitor tomorrow night!
