### ISSUE TITLE
Home page slider timing

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#37]
I know you said this was a bit tricky, but is there anything we can do to fix the timings on the sliders on the home page? They're a bit out of whack!

**Comment by deringer** [comment]
It's tricky because Divi starts the slider animation as soon as the content is ready. Because the images are larger in size than their text counterparts, they take slightly longer to load, and thus longer for the animations to start.

This will change from device to device, and again depending on connection speed, so whilst we tinker with timings to fix it in a specific case, it's not necessarily going be helpful even for the next time you reload the page.

Realistically, the only way to *fix* the timing issues, is by having a single slider with text on it, but then that'll mean you won't get the text at all on smaller screen devices.

**Comment by leah-wuttke** [comment]
I sent you an email based on what we discussed. If we could then just have the 'Adelaide's Largest Health Food Store' slide on the left as static, that would be great.
